version: "3.5"

networks:
        localhost:
                name: inet

volumes:
        wordpress:
                name: wordpress
                driver: local
                driver_opts:
                        device: /home/jsiller/data/wordpress
                        o: bind
                        type: none
        mariadb:
                name: mariadb
                driver: local
                driver_opts:
                        device: /home/jsiller/data/mariadb
                        o: bind
                        type: none


services:
        nginx:
                depends_on:
                        - wordpress
                container_name: nginx_debian
                build: ./requirements/nginx
                image: nginx
                ports:
                        - "443:443"
                volumes:
                        - wordpress:/var/www/wordpress
                networks:
                        - localhost
                restart: always
        mariadb:  
                container_name: mariadb_debian
                build: ./requirements/mariadb
                volumes:
                        - mariadb:/var/lib/mysql
                networks:
                        - localhost
                image: mariadb
                restart: always
        wordpress:
                depends_on:
                        - mariadb
                container_name: wordpress_debian
                build: ./requirements/wordpress
                image: wordpress
                volumes:
                        - wordpress:/var/www/wordpress
                networks:
                        - localhost
                restart: always
                environment:
                  - DB_NAME=$DB_NAME
                  - DB_USER=$DB_USER
                  - DB_PASSWORD=$DB_PASSWORD
                  - DB_HOST=$DB_HOST
                  - WP_TITLE=$WP_TITLE
                  - WP_ADMIN_USER=$WP_ADMIN_USER
                  - WP_ADMIN_PASSWORD=$WP_ADMIN_PASSWORD
                  - WP_ADMIN_MAIL=$WP_ADMIN_MAIL
                  - WP_USER=$WP_USER
                  - WP_USER_MAIL=$WP_USER_MAIL
                  - WP_USER_PASSWORD=$WP_USER_PASSWORD
                  - WP_URL=$WP_URL
        webpage:
                container_name: webpage_debian
                build: ./bonus/webpage
                image: webpage
                networks:
                      - localhost
                restart: always
        adminer:
                container_name: adminer_debian
                build: ./bonus/adminer
                image: adminer
                networks:
                      - localhost
                volumes:
                      - wordpress:/var/www/wordpress
                restart: always
                depends_on:
                        - wordpress