FROM debian:buster

RUN apt-get update
RUN apt-get install -y php7.3 php-mysqli php-fpm mariadb-client

COPY ./www.conf /etc/php/7.3/fpm/pool.d

ADD https://wordpress.org/latest.tar.gz /var/www/latest.tar.gz
RUN cd /var/www && tar -xvf latest.tar.gz

COPY ./wp-config.php /var/www/wordpress/wp-config.php
RUN mkdir /run/php
CMD ["php-fpm7.3", "-F"]


